# Generated by Django 4.2.6 on 2023-10-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestant.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.question')),
                ('selectedOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.option')),
            ],
        ),
    ]
